apiVersion: v1
kind: Secret
metadata:
  name: ${profile.application.name}-kieserver-secret
stringData:
  url: http://${profile.application.name}-kieserver.${profile.openshift.project}.svc/kie-server
  username: ${profile.kieserver.username}
  password: ${profile.kieserver.password}
