spec:
  replicas: 1
  template:
    spec:
      containers:
        - env:
          - name: PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name:  ${profile.application.name}-db-secret
                key: password
          - name: PG_USERNAME
            valueFrom:
              secretKeyRef:
                name:  ${profile.application.name}-db-secret
                key: username
          - name: MAVEN_MIRROR_URL
            value: ${maven.mirror.url}
